CREATE TABLE audit_records (
    id BINARY(16) NOT NULL,
    tenant_id BINARY(16) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6),
    created_by VARCHAR(255) NOT NULL,
    updated_by VARCHAR(255),
    source_service VARCHAR(255) NOT NULL,
    source_event_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    occurred_at DATETIME(6) NOT NULL,
    correlation_id VARCHAR(255),
    actor_id BINARY(16),
    entity_type VARCHAR(255),
    entity_id VARCHAR(255),
    payload TEXT NOT NULL,
    record_hash VARCHAR(64) NOT NULL,
    previous_record_hash VARCHAR(64),
    retain_until DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_audit_record_source_event UNIQUE (source_service, source_event_id),
    INDEX idx_audit_chain_lookup (tenant_id, source_service, created_at),
    INDEX idx_audit_entity_trail (tenant_id, entity_type, entity_id),
    INDEX idx_audit_actor_activity (tenant_id, actor_id, created_at),
    INDEX idx_audit_retention (retain_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
