package com.saas.auditcompliance.enums;

public enum SourceService {
    FINANCE_ADMINISTRATION,
    BUDGET_MANAGEMENT,
    GENERAL_LEDGER,
    CASH_BANKING,
    ACCOUNTS_PAYABLE,
    ACCOUNTS_RECEIVABLE,
    EMPLOYEE_FINANCE,
    ASSET_INVENTORY_FINANCE,
    FINANCIAL_REPORTING,
    AUDIT_COMPLIANCE
}